name = "backend"
compatibility_date = "2023-12-01"

[vars]
JWT_SECRET="10366c2a-e10e-431d-b08e-ceeecae1c231"
DIRECT_DATABASE_URL="postgresql://sparshsingh7586:dh4anfV0GAoN@ep-long-cell-29801479.us-east-2.aws.neon.tech/sociopath?sslmode=require"
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiOTYyMTc3YTgtOTlmYy00NmYwLWFhYWYtZjI4YjEyNjZlNmYxIiwidGVuYW50X2lkIjoiZmRlY2IzZjg2MjU5OTEwOGY3ZjJhNDRiOTQyMjVjZjc5YjgwMGZiMWRlNWJiOTA4ZTVjNTA0MTg5YzAzYzIzNiIsImludGVybmFsX3NlY3JldCI6IjQ2YzdhZDg1LWM0YTAtNDNhYy04MjhiLTM0M2U0NGQ3YTIwMyJ9.ssg1jUam-9lTys5vbyqOSi5-QTldtr0ImcQWGrncBPE"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""
